

name: Java CI - Mvn + GHub + Dckr + JFrog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildApp:
    
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - checkout the code
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Step 3 - Compile code
      run: mvn compile 

    - name: Step 4 - Build package
      run: mvn package -DskipTests

    - name: Step 5 - Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: vetClinic-jar
        path: ${{ github.workspace }}/target/*.jar
        retention-days: 1

  
  buildImage:

    runs-on: ubuntu-latest
    needs: buildApp

    steps:
    - name: Step 6 - Download jar
      uses: actions/download-artifact@v1
      with:
          name: vetClinic-jar
          path: .

    - name: Step 7 - Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
    #- uses: actions/checkout@v3
    #- uses: actions/setup-java@v3
    #  with:
    #    java-version: '17'
    #    distribution: 'temurin'
    #- run: mvn --batch-mode --update-snapshots verify
    #- run: mkdir staging && cp target/*.jar staging
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: Package
    #    path: staging
