

name: Java CI - Mvn + GHub + Dckr + JFrog

on:
  push:
    branches: [ "main" ]

jobs:
  buildApp:
    
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - checkout the code
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Step 3 - Compile the code
      run: mvn -B compile     

    #- name: Step 4 - Run the tests
      #run: mvn test

    - name: Step 5 - Package the project as a runnable Docker image
      run: | 
        mvn -B package -DskipTests   
    
    - uses: mr-smithers-excellent/docker-build-push@v6
      with:
        #below for dockerhub
        #image: dsener/petclinic2
        image: ilay-docker/pet-clinic2
        tags: latest
        registry: ilaysener.jfrog.io
        #below for dockerhub registry
        #registry: registry.hub.docker.com
        #publish images for linux amd64 and arm64 architectures (I am using mac M1)
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        username: ${{ secrets.JF_USERNAME }}
        password: ${{ secrets.JF_TOKEN }}
        #dockerhub credentials
        #username: ${{ secrets.DOCKERHUB_USERNAME }}
        #password: ${{ secrets.DOCKERHUB_TOKEN }}

    
#    - name: Step 8 - Build Docker image
#      run: |
#        docker build . -t dsener/petclinic2:latest        

#    - name: Step 9 - Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

 #   - name: Docker push
 #     run: docker push dsener/petclinicmulti:latest


