

name: Java CI - Mvn + GHub + Dckr + JFrog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildApp:
    
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - checkout the code
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Step 3 - Compile code
      run: mvn compile 

    - name: Step 5 - Build package
      run: mvn package 

    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/my-app/target/*.jar
        retention-days: 1

  
#  buildImage:

    #runs-on: ubuntu-latest
    #needs: buildApp

    #steps:
    #- uses: actions/checkout@v3
    #- uses: actions/setup-java@v3
    #  with:
    #    java-version: '17'
    #    distribution: 'temurin'
    #- run: mvn --batch-mode --update-snapshots verify
    #- run: mkdir staging && cp target/*.jar staging
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: Package
    #    path: staging
