

name: Java CI - Mvn + GHub + Dckr + JFrog

on:
  push:
    branches: [ "main" ]

jobs:
  buildApp:
    
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - checkout the code
      uses: actions/checkout@v3

    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Step 3 - Compile the code
      run: mvn -B compile     

    - name: Step 4 - Run the tests
      run: mvn test

    
    
  
    - name: Step 5 - Package the project as a runnable Docker image
      run: | 
        mvn -B package -DskipTests
        # The following is necessary as .dockerignore has reference to 'target' folder. You can remove the below if you exclude 'target' 
        # folder from the .dockerignore.
        cp target/spring-petclinic-*.jar spring-petclinic.jar  
        
    
  

 
    - name: Step 8 - Build Docker image
      run: |
        docker build . -t dsener/petclinic2:latest --platform=linux/arm64

    - name: Step 9 - Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker push
      run: docker push dsener/petclinic2:latest

#    - uses: mr-smithers-excellent/docker-build-push@v6
#      name: Build & push Docker image
#      with:
#        image: dsener/petclinic2
#        tags: latest
#        #registry: ilaysener.jfrog.io
#        registry: registry.hub.docker.com
#          #publish images for x84 and arm 64 architectures
#        multiPlatform: true
#        platform: linux/amd64,linux/arm64
#        #dockerfile: ./Dockerfile
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    

